default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["RECIPE_DB_USERNAME"] %>
  password: <%= ENV["RECIPE_DB_PASSWORD"] %>
  host: localhost

development:
  database: recipes_dev
  <<: *default

test:
  database: recipes_test
  <<: *default

production:
  database: recipes_prod
  <<: *default
