defaults: &defaults
  mandrill_user: add_value
  mandrill_pw: add_value
  omni_google_id: add_value
  omni_google_key: add_value
  omni_facebook_id: add_value
  omni_facebook_key: add_value
  omni_twitter_id: add_value
  omni_twitter_key: add_value

development:
  <<: *defaults
  secret_key_base: add_value

test:
  <<: *defaults
  secret_key_base: add_value

production:
  <<: *defaults
  omni_google_id: add_value
  omni_google_key: add_value
  omni_facebook_id: add_value
  omni_facebook_key: add_value
  omni_twitter_id: add_value
  omni_twitter_key: add_value
  secret_key_base: add_value
